### ISSUE TITLE
User Permissions should reflect roles permissions if permissions are empty

### ISSUE THREAD

**Issue by juneX05** [juneX05/api-backend#9]
We are adding user permissions to reflect roles permissions if incase the permissions array is empty so as to make sure that each user has a specific set of permission initially just after being added into the system

**Comment by SwahnglishCoderz** [comment]
I was thinking due to the corrections we made on the client we should leave this untouched. So that it can handle what the client offers and not predict what the client might want.

**Comment by juneX05** [comment]
Agreed. For that case I will close this issue then since we have nothing to do with it
